### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Hardik25-iso** [Sharmeen20/To-Do-List-Application#13]
Functionality Duplication: The save_tasks function writes to a file every time a task is added, removed, or modified, which can lead to performance issues if many changes are made in quick succession. Instead, it can be called once when exiting the program.

Error Handling: There are some areas where error handling could be improved, such as when parsing integers or handling invalid input. Adding more specific error messages can help the user.

Task Deadline Formatting: The code does not handle cases where the deadline is entered in an incorrect format gracefully. It would be better to provide feedback to the user without letting the program crash.

Code Structure: Some functions could benefit from improved readability and organization. For instance, using constants for file paths or magic strings could improve maintainability.

User Experience: The user interface could be improved by providing clearer messages and allowing users to see the current state of the tasks after certain actions.

**Comment by roshankraveendrababu** [comment]
please i assign me this issue. i will solve this diligently and will solve it successfully by learning new concepts on the way . this will ensure my professional devolopment. please consider my comment.
