### ISSUE TITLE
Missing datetime import in main file

### ISSUE THREAD

**Issue by UmeshIsu** [Sharmeen20/To-Do-List-Application#9]
There is an issue in the main file where the `datetime` module is used but not imported.

Affected Code:
- The `add_task` function uses `datetime.strptime()` to parse the deadline, but the `datetime` module is not imported, which will result in a `NameError`.

Suggested Fix:
- Add the following import statement at the top of the file:
  ```python
  from datetime import datetime

**Comment by roshankraveendrababu** [comment]
please assign me this issue if it is not closed i will solve it successfully . this will help me enormously. please consider my comment!!

**Comment by UmeshIsu** [comment]
@roshankraveendrababu  It is fixed.
